# 
# Thank you for downloading and using AFK V4.5.1
# Minecraft 1.10.2
# ***************************************************
# Events: def. Move False, Chat true
# Colors: def. gray [black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white]
# IdleTimer: def. true, 120 sec
# Messages: def. true (keys: {DISPLAYNAME}, {TIME})
Events:
  move: true
  chat: true
Colors:
  message: gray
  player: gray
IdleTimer:
  enabled: true
  period: 120
Messages:
  enabled: true
  nicknames: false
  +afk: '{DISPLAYNAME} is now AFK'
  -afk: '{DISPLAYNAME} was AFK for {TIME} but is back now'
